from .aule import ModelAule
from .libri import ModelLibri
from .libri_osservati import ModelLibriOsservati
from .operatori import ModelOperatori
from .posti import ModelPosti
from .prenotazioni_libri import ModelPrenotazioniLibri
from .prenotazioni_posti import ModelPrenotazioniPosti
from .prestiti import ModelPrestiti
from .sanzioni import ModelSanzioni
from .statistiche import ModelStatistiche
from .users import ModelUsers
from .utenti import ModelUtenti
