from utils import hash_password, to_year

UTENTI = [{"nome": "Mario",
           "cognome": "Rossi",
           "ruolo": "admin",
           "username": "S001",
           "password": hash_password("admin")},
          {"nome": "Giulio",
           "cognome": "Bianchi",
           "ruolo": "operatore",
           "username": "S002",
           "password": hash_password("operatore")},
          {"nome": "Dario",
           "cognome": "Verdi",
           "ruolo": "utente",
           "username": "S003",
           "password": hash_password("utente")},
          ]

LIBRI = [{"titolo": "Fisica. Vol. 1: Meccanica, termodinamica",
          "autori": "Paolo Mazzoldi, Massimo Nigro, Cesare Voci",
          "immagine": "fisica_1.jpg",
          "editore": "Edises",
          "isbn": "0471958697",
          "anno_edizione": to_year("2000"),
          "anno_pubblicazione": to_year("2000"),
          "disponibili": 3,
          "dati": "583 p., ill., 2 ed."},
         {"titolo": "Fisica. Vol. 2: Elettromagnetismo, onde",
          "autori": "Paolo Mazzoldi, Massimo Nigro, Cesare Voci",
          "immagine": "fisica_2.jpg",
          "editore": "Edises",
          "isbn": "0306406152",
          "anno_edizione": to_year("1998"),
          "anno_pubblicazione": to_year("1998"),
          "disponibili": 4,
          "dati": "792 p., ill., brossura, 2 ed."},
         {"titolo": "Sistemi operativi",
          "autori": "Abraham Silberschatz, Peter Baer Galvin, Greg Gagne",
          "immagine": "sistemi_operativi.jpg",
          "editore": "Pearson",
          "isbn": "123456789X",
          "anno_edizione": to_year("2019"),
          "anno_pubblicazione": to_year("2019"),
          "disponibili": 2,
          "dati": "1 voll., XXXIV-860 p., 10 ed."},
         {"titolo": "Ricerca operativa",
          "autori": "Massimo Pappalardo, Mauro Passacantando",
          "immagine": "ricerca_operativa.jpg",
          "editore": "Pisa University Press",
          "isbn": "123456789X",
          "anno_edizione": to_year("2013"),
          "anno_pubblicazione": to_year("2013"),
          "disponibili": 0,
          "dati": "374 p., brossura, 2 ed."},
         {"titolo": "Piccole abitudini per grandi cambiamenti",
          "autori": "James Clear",
          "immagine": "atomic_habits.jpg",
          "editore": "De Agostini",
          "isbn": "123456789X",
          "anno_edizione": to_year("2019"),
          "anno_pubblicazione": to_year("2019"),
          "disponibili": 3,
          "dati": "332 p., ill., brossura"},
         ]
