from enum import Enum


class KeyDb(Enum):
    LIBRO = "DB_LIBRO"
    PRENOTAZIONE_LIBRO = "DB_PRENOTAZIONE_LIBRO"


class KeyModel(Enum):
    LIBRO = "MODEL_LIBRI"
    PRENOTAZIONE_LIBRO = "MODEL_PRENOTAZIONI_LIBRI"


class Key(Enum):
    CATALOGO = "CATALOGO"
    TEXT = "TEXT"
    CONTESTO = "CONTESTO"


class KeyButtonComponent(Enum):
    VISUALIZZA_LIBRO = "BUTTON_COMPONENT_VISUALIZZA_LIBRO"
    PRENOTA_LIBRO = "BUTTON_COMPONENT_PRENOTA_LIBRO"
    OSSERVA_LIBRO = "BUTTON_COMPONENT_OSSERVA_LIBRO"
    DETTAGLI_PRENOTAZIONE_LIBRO = "BUTTON_COMPONENT_"
    CANCELLA_PRENOTAZIONE_LIBRO = "BUTTON_COMPONENT_"
    GO_TO_LIBRI_PRENOTATI = "BUTTON_COMPONENT_"
    #  = "BUTTON_COMPONENT_"


class KeyAuth(Enum):
    ADMIN = "AUTH_ADMIN"
    OPERATORE = "AUTH_OPERATORE"
    UTENTE = "AUTH_UTENTE"
    GUEST = "AUTH_GUEST"

