from .catalogo import CatalogoController
from .libri import ControllerLibri
from .libri_osservati import ControllerLibriOsservati
from .login import LoginController
from .logout import ControllerLogout
from .notifiche import ControllerNotifiche
from .operatori import ControllerOperatori
from .prenotazioni_libri import ControllerPrenotazioniLibri
from .prenotazioni_posti import ControllerPrenotazioniPosti
from .prestiti import ControllerPrestiti
from .router import ControllerRouter
from .sanzioni import ControllerSanzioni
from .statistiche import ControllerStatistiche
from .utenti import ControllerUtenti
